### PR TITLE
Smooth lava balls into the ground @ zero-intercept

### PR DESCRIPTION
**Pull request by aleksanb**
screenshot from 2014-07-11 18 07 21

### CODE REVIEW

**Comment by iver56** [comment]
Undoobify code style, please?

**Comment by aleksanb** [comment]
Not untill we decide on a common coding standard.

**Comment by sigvef** [comment]
Ok, I decide on the non-doob standard.

**Comment by stianjensen** [comment]
+1 on the non-doob standard.

**Comment by aleksanb** [comment]
Not good enough. If we reject doom spaces after parentheses, we should also be strict on spaces after ifs- etc

**Comment by cristeahub** [comment]
+1 on non-doob coding style

**Comment by aleksanb** [comment]
https://gist.github.com/zz85/e929503387cdc597b4f7

**Pull request merged**
