### PR TITLE
Add some lens distortion, vignette post effects

### PR DESCRIPTION
**Pull request by sigvef**

### CODE REVIEW

**Comment by stianjensen** [comment]
`Space Bloom` crashes because no config is set.

**Comment by stianjensen** [comment]
Also, please rebase :baby_chick:

**Comment by sigvef** [comment]
ping

**Comment by stianjensen** [comment]
Please rebase. Again :)

**Comment by sigvef** [comment]
ping

**Comment by stianjensen** [comment]
Please rebase. :dancers:

**Comment by sigvef** [comment]
ping

**Pull request merged**
