### PR TITLE
Dont run vignette

### PR DESCRIPTION
**Pull request by Raane**
Removing vignette from layers.json as it breaks alot of our dev enviroments

### CODE REVIEW

**Comment by peterhgombos** [comment]
Please don't add additional commits.

**Comment by Raane** [comment]
Fixed

**Comment by peterhgombos** [comment]
Please do not try to sneak in other code in your commit.

**Comment by Raane** [comment]
Wat... Will fix...

**Comment by peterhgombos** [comment]
My mistake, cache is not always king.

**Pull request merged**
