### PR TITLE
A simple heat haze shader

### PR DESCRIPTION
**Pull request by Raane**
This is a simle heat haze shader. I don't know how "finished" our effects should be before being added to master, or if it should be added to master but not the layers file or what. Let me know how we are doing this if it is not ready enough. It can be used as is, to try it out together with other demo effects.

This is more of a draft, and need to have a few parameters added before it is really ready. It should at least have parameters for fading in and out, a parameter to controll the effects strength and a parameter to tell the shader where the horizont is.

### CODE REVIEW

**Comment by stianjensen** [comment]
Please rebase against master :ice_cream:

**Comment by Raane** [comment]
Hmm... Somehow I fucked up the last rebase so that master was not there as intended, but a random commit by Iver was. Oh well, should be fixed now.

**Comment by stianjensen** [comment]
Cool, and now amount may be controlled from javascript?

**Comment by Raane** [comment]
No, this is just so that people can use the layer to check out how the effect works out with other stuff. The parameter controlls still need to be added.

I don't know how strict we are running this project. If all features are supposed to be complete before being added to master, just close the pull request and I will reopen it when it is complete.

**Comment by Raane** [comment]
Ok, this is ready now with uniforms to control the heat haze shader from the javascript layer.

**Pull request merged**
